# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, nixos-hardware, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      nixos-hardware.nixosModules.framework
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "uas" "usbhid" "usb_storage" "sd_mod" "nvme" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.tmpOnTmpfs = true;
 
  # boot.initrd.luks.devices."external".device = "/dev/disk/by-uuid/76d7740a-dc5d-4a17-b730-4ba388902b08";
  boot.initrd.luks.devices."internal" = {
    device = "/dev/disk/by-uuid/e9c87df3-a5b1-4765-8da6-d055c26d3323";
    # Doesn't work - root fs has to be mounted before this can be performed.
    # keyFile = "/crypto_keyfile.bin";
    # preLVM = false;
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c62cfd16-31eb-4d3d-bfdc-7917349bcb2d";
      fsType = "btrfs";
    };

  fileSystems."/var" =
    { device = "/dev/disk/by-uuid/2ef8cb69-ab57-46d9-9c55-253219556f7d";
      fsType = "xfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c5eff277-94f0-4d87-894d-6075737eb1a3";
      fsType = "btrfs";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/F69C-D9F4";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-partuuid/78059e35-0cc9-4183-af14-1c12eb8322f8";
	randomEncryption = true; }
    ];


  powerManagement.enable = true;
  powerManagement.cpuFreqGovernor = "ondemand";
  hardware.cpu.intel.updateMicrocode = config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = true;
  
  security.pam.services.login.fprintAuth = false;
  security.pam.services.xscreensaver.fprintAuth = false; 
  services.fprintd.enable = false;
  
  services.thermald.enable = true;
}
