# This example uses YAML anchors which allows reuse of multiple keys
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/d6114726d859df36ccaa32891c4963ae5717ef7f/nixos/.sops.yaml
# for a more complex example.
keys:
  - &lukas-LsWootingMBP age1mm8ejmjpmnepjjdvxnqj9twlee85fe9dl3l7ws2ujeeehk9nj5rsty3s8c
  - &LsWootingMBP age1m6zyqeydal8weye55lag3pw24k45rp0xst23r2hvpd9xjnqsu49qzy3zh5
  - &LsAir age1yp8zxc8yn8af7numgt069cwe85yzgsyjec08x26sy606ap3z6g4qqqz5xd
  - &keybase-gpg-fpr EAB800957676ADBE2E29E1B61F748B25B736F0A8
  - &LsFramework age1akdwemj3v9w3hczj3xa6tdalcfa0mx2p0hsuhrzjakc5thndrv0she82w5
  - &sd-161581 age1x94ufwycmr4qqzlaj5963vvn3l8qnrn7z09dm5z4tdk35ze5guxsl32prh
creation_rules:
  - path_regex: ^darwin/LsWootingMBP/secrets/[^/]+$
    age:
    - *lukas-LsWootingMBP
    - *LsWootingMBP
  - path_regex: ^darwin/LsAir/secrets/[^/]+$
    age:
    - *LsAir
    pgp:
    - *keybase-gpg-fpr
  - path_regex: ^secrets/[^/]+$
    age:
    - *lukas-LsWootingMBP
    gpg:
    - *keybase-gpg-fpr
  - path_regex: ^nixos/framework/secrets/[^/]+$
    age:
    - *LsFramework
    pgp:
    - *keybase-gpg-fpr
  - path_regex: ^nixos/sd-161581/secrets/[^/]+$
    age:
    - *sd-161581
    pgp:
    - *keybase-gpg-fpr
