function! LoadFile(var)
  if filereadable(a:var)
    exec 'source ' . a:var
  endif
endfunction

call LoadFile('/etc/vimrc')
call LoadFile($HOME . '/.vim-vundlerc')

set nu " Show line numbers
set nocompatible " We're running Vim, not Vi!
syntax on " Enable syntax highlighting
filetype plugin indent on " Enable filetype detection

set tabstop=2 " <Tab> equals to 2x <Space>
set shiftwidth=2 " Equal to tabstop
set expandtab " Always insert <Space>s instead of <Tab>s

set incsearch " Show where pattern so far matches
set smartcase " Ignore case of letters if pattern contains only lowercase
set hlsearch " Highlight occurences of pattern

set foldmethod=syntax " Syntax highlighting items specify folds.
set foldlevel=2 " Start folding when nested 2 times

set t_Co=256 " Use 256 colours
set background=dark " Dark background
color solarized " Solarized color scheme

set showcmd	" Show (partial) command in status line.
set showmatch	" Show matching brackets.
set mouse=a	" Enable mouse usage (all modes)
set ttyfast " Force fast terminal
set ttymouse=urxvt " Force mouse handling for urxvt
set laststatus=2 " Always show statusline
set backspace=indent,eol,start " Backspace works as expected
set hidden " Don't force saving buffers when leaving them

call LoadFile($HOME . '/.vim-pluginrc')
call LoadFile($HOME . '/.vim-bindrc')
