call pathogen#infect()
call pathogen#helptags()

set nu

set tabstop=2 shiftwidth=2 expandtab

set tags=./.tags

nmap <F2> :%!astyle --mode=cs --style=stroustrup -p -s2<cr>

:nmap \o :set paste!<CR>
:nmap j gj
:nmap k gk
:map <C-a>  <Home>
:map <C-e>  <End>
:nmap \h  :MBEbp<CR>
:nmap \l  :MBEbn<CR>
:map <C-b>  <PageUp>
:map <C-f>  <PageDown>
:map \p <C-p>

:cnoremap <C-d>  <Delete>
:cnoremap <M-b>  <S-Left>
:cnoremap <M-f>  <S-Right>
:cnoremap <M-d>  <S-right><Delete>
:cnoremap <Esc>b <S-Left>
:cnoremap <Esc>f <S-Right>
:cnoremap <Esc>d <S-right><Delete>
:cnoremap <C-g>  <C-c>

:set incsearch
:set ignorecase
:set smartcase
:set hlsearch
:nmap \q :nohlsearch<CR>

ino <silent> <Leader><tab> <c-r>=TriggerSnippet()<cr>
snor <silent> <Leader><tab> <esc>i<right><c-r>=TriggerSnippet()<cr>


:nmap ; :CtrlP<CR>

:let g:ctrlp_map = '<Leader>t'
:let g:ctrlp_match_window_bottom = 0
:let g:ctrlp_match_window_reversed = 0
:let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend|hi|ho)$|(^|[/\\])\.(hg|git|bzr)($|[/\\])|__init__\.py|node_modules'
:let g:ctrlp_working_path_mode = "r"
:let g:ctrlp_dotfiles = 0
:let g:ctrlp_switch_buffer = 0

:let g:rainbow_active = 1
:let g:rainbow_conf = {
      \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
      \   'ctermfgs': ['142', '26', '199', '122', '196', '46'],
      \   'operators': '_,_',
      \   'parentheses': [['(',')'], ['\[','\]'], ['{','}']],
      \   'separately': {
      \       'html': {
      \           'parentheses': [['(',')'], ['\[','\]'], ['{','}'], ['<\a[^>]*[^/]>\|<\a>','</[^>]*>']],
      \       },
      \       'tex': {
      \           'operators': '',
      \           'parentheses': [['(',')'], ['\[','\]']],
      \       },
      \   }
      \}

:nmap \e :NERDTreeToggle<CR>
:nmap \a :bnext<CR>
:nmap \s :bprev<CR>
:nmap \d :bd<CR>

:nmap \t :set expandtab tabstop=4 shiftwidth=4 softtabstop=4<CR>
:nmap \T :set expandtab tabstop=8 shiftwidth=8 softtabstop=4<CR>
:nmap \M :set noexpandtab tabstop=8 softtabstop=4 shiftwidth=4<CR>
:nmap \m :set expandtab tabstop=2 shiftwidth=2 softtabstop=2<CR>


runtime! debian.vim

if has("syntax")
  syntax on
endif

set t_Co=256
set background=dark
color solarized

if has("autocmd")
  filetype plugin indent on
endif

set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set mouse=a		" Enable mouse usage (all modes)
set ttyfast
set ttymouse=xterm2

let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
set laststatus=2
let g:miniBufExplorerAutoStart = 0

let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
let g:indent_guides_auto_colors=0
hi IndentGuidesOdd  ctermbg=24
hi IndentGuidesEven ctermbg=25

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
