(require 'fuzzy)
(require 'yasnippet)
(require 'auto-complete-config)
(require 'semantic)
(yas-global-mode 1)
(semantic-mode 1)
(setq ac-auto-show-menu 0.0)
(setq ac-use-fuzzy t)
(setq ac-comphist-file "/tmp/ac-comphist.dat")
(ac-config-default)
(ac-set-trigger-key "TAB")
(ac-set-trigger-key "<tab>")
