source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" noload

plug "andreyorst/fzf.kak"
plug "andreyorst/kaktree" defer kaktree %{
    set-option global kaktree_double_click_duration '0.5'
    set-option global kaktree_indentation 1
    set-option global kaktree_dir_icon_open  '▾ '
    set-option global kaktree_dir_icon_close '▸ '
    set-option global kaktree_file_icon      '⠀⠀'
} config %{
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
    kaktree-enable
}

plug "lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
}

plug "sjjf/puppet-kak"

map global normal <c-p> ': fzf-mode<ret>'
map global normal <c-r> ': kaktree-toggle<ret>'

add-highlighter global/ wrap
add-highlighter global/ number-lines
