#!/bin/bash

## script to switch screen rotation -- uses /usr/bin/rotate
ROTATE=/usr/bin/rotate

#############################################################
#                                                           #
# by Lukasz Czapliński                                      #
# based on http://ubuntuforums.org/showthread.php?t=2116275 #
#             written by ATXChris             	            #
#					                                                  #
#############################################################
ROTATIONS='(normal|right|inverted|left)'
rotation=$( xrandr -q --verbose | grep 'connected' | \
  egrep -o  "\) $ROTATIONS \(" | egrep -o "$ROTATIONS" )

case $rotation in
  normal)
    target=inverted
    ;;
  right)
    target=normal
    ;;
  left)
    target=normal
    ;;
  inverted)
    target=normal
    ;;
esac

echo "Switching to $target"
$ROTATE -r $target
