#!/bin/zsh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PKGLIST=$DIR/etc/pkglist.txt

for PKGNAME in $@
do
  echo -e "Searching for $PKGNAME.. "
  if [[ X"  " = X" $( cat $PKGLIST | grep -w $PKGNAME ) " ]] 
  then 
    echo "Not found, adding."; echo "$PKGNAME" >> $PKGLIST; 
    else
    echo "Found."
  fi
done
