#!/bin/bash

function usage {
  echo " Usage: $0 [--help] { url | path } "
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd ../ &&  pwd )"
LIST="$DIR/gitrepos.list"

case $@ in
  "" )
    usage ;;
  "--help" )
    usage ;;
  "url" )
    URLs="$( grep URL= $LIST )"
    for URL in $URLs
    do
      echo "${URL#*=}"
    done ;;
  "path" )
    PATHs="$( grep PATH= $LIST )"
    for PATH in $PATHs
    do
      echo "${PATH#*=}"
    done ;;
esac
