(defun elixir-mix-format-code ()
  (interactive)
  (shell-command-to-string (format "mix format %s" buffer-file-name)))

(defun elixir-remove-do-sugar ()
  (interactive)
  (save-excursion
    (elixir-beginning-of-defun)
    (goto-char (line-end-position))
    (backward-kill-word 1)
    (delete-horizontal-space)
    (insert ", do:")
    (forward-line 1)
    (delete-indentation)
    (forward-line 1)
    (kill-whole-line)))
