#!/bin/bash
export LC_ALL=en_GB.UTF-8
export LANG=en_GB.utf-8

function _scoiatael_maybe_PATH_add() {
    [ -z "$VERBOSE" ] || log_status "Trying dir $1.."
    if test -d "$p";
    then
        PATH_add "$p"
    fi
}

function _scoiatael_launch_gpg_agent() {
    if [ "Linux" = "$(uname)" ]; then
        systemctl --user enable --now 'gpg-agent.socket'
    else
        gpgconf --launch gpg-agent
    fi
}


function _scoiatael_init() {
    [ -z "$VERBOSE" ] || log_status "Start init.."
    export GOPATH=$HOME/go
    PATH_add "$GOPATH/bin"

    [ -z "$VERBOSE" ] || log_status "Extending PATH.."
    _scoiatael_maybe_PATH_add "/usr/local/bin"
    _scoiatael_maybe_PATH_add "/usr/local/sbin"
    _scoiatael_maybe_PATH_add "$HOME/.local/bin"
    _scoiatael_maybe_PATH_add "/usr/local/opt/go/libexec/bin"
    _scoiatael_maybe_PATH_add "$HOME/.cargo/bin"
    _scoiatael_maybe_PATH_add "$GOPATH/bin"
    _scoiatael_maybe_PATH_add "/usr/local/opt/texinfo/bin"
    _scoiatael_maybe_PATH_add "/usr/local/MacGPG2/bin"
    _scoiatael_maybe_PATH_add "~/.emacs.d/bin"
    _scoiatael_maybe_PATH_add "/opt/puppetlabs/pdk/bin"

    [ -z "$VERBOSE" ] || log_status "Starting GPG agent.."
    local ssh_agent
    ssh_agent="$(gpgconf --list-dirs agent-ssh-socket)"
    if [ -z "$SSH_AUTH_SOCK" ] || [ "$SSH_AUTH_SOCK" != "$ssh_agent" ];
    then
        [ -z "$VERBOSE" ] || log_status "Agent dead or missing; starting new"
        _scoiatael_launch_gpg_agent;
        export SSH_AUTH_SOCK=$ssh_agent
    fi

    PATH_add "$HOME/.emacs.d/bin"
    [ -z "$VERBOSE" ] || log_status "Done."
}

_scoiatael_init > /dev/null

source $(asdf which direnv_use_asdf)
