#!/bin/bash

export LC_ALL=en_GB.UTF-8

function _scoiatael_maybe_PATH_add() {
    [ -z "$VERBOSE" ] || log_status "Trying dir $1.."
    if test -d "$p";
    then
        PATH_add "$p"
    fi
}

function _scoiatael_launch_gpg_agent() {
    if [ "Linux" = "$(uname)" ]; then
        systemctl --user enable --now 'gpg-agent.socket'
    else
        gpgconf --launch gpg-agent
    fi
}


function _scoiatael_init() {
    [ -z "$VERBOSE" ] || log_status "Start init.."
    export GOPATH=$HOME/go
    PATH_add "$GOPATH/bin"

    PATH_add "$HOME/.cargo/bin"
    RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
    export RUST_SRC_PATH

    [ -z "$VERBOSE" ] || log_status "Extending PATH.."
    for p in /usr/local/bin /usr/local/sbin $HOME/.local/bin $HOME/Library/Python/2.7/bin /usr/local/opt/go/libexec/bin $HOME/.cargo/bin $GOPATH/bin $HOME/dotfiles/bin /usr/local/opt/texinfo/bin;
    do
        _scoiatael_maybe_PATH_add "$p";
    done

    [ -z "$VERBOSE" ] || log_status "Starting GPG agent.."
    local ssh_agent
    ssh_agent="$(gpgconf --list-dirs agent-ssh-socket)"
    if [ -z "$SSH_AUTH_SOCK" ] || [ "$SSH_AUTH_SOCK" != "$ssh_agent" ];
    then
        [ -z "$VERBOSE" ] || log_status "Agent dead or missing; starting new"
        _scoiatael_launch_gpg_agent;
        export SSH_AUTH_SOCK=$ssh_agent
    fi

    [ -z "$VERBOSE" ] || log_status "Loading agent.."
    if ! ssh-add -l | grep -v 'no identities';
    then
        if ! ssh-add -A 2> /dev/null;
        then
            ssh-add
        fi
    fi

    [ -z "$VERBOSE" ] || log_status "Loading opam.."
    if command opam > /dev/null 2> /dev/null;
    then
        eval "$(opam config env --shell=bash)"
    fi

    export NODE_VERSIONS="$HOME/.node"
    mkdir -p "$NODE_VERSIONS"

    export GTAGSLABEL=pygments
    [ -z "$VERBOSE" ] || log_status "Done."
}

_scoiatael_init > /dev/null

use_ruby() {
    local ruby_root=$HOME/.rubies/ruby-$1
    load_prefix "$ruby_root"
    layout_ruby
}

use_go() {
    GOPATH="$PWD:$(go env GOPATH)"
    export GOPATH
    PATH_add "$PWD/bin"
}

export LANG=en_GB.utf-8
