# $XDG_CONFIG_HOME/process-compose/shortcuts.yaml
shortcuts:
  log_follow:
    shortcut: Ctrl-F
  log_screen:
    shortcut: Ctrl-L
  log_wrap:
    shortcut: Ctrl-W
  process_restart:
    shortcut: Ctrl-R
  process_screen:
    shortcut: Ctrl-P
  process_stop:
    shortcut: Ctrl-Z
  quit:
    shortcut: Ctrl-Q
